### ISSUE TITLE
[Bug] Default settings for Wake-Up time not working since V1.2.0 [WINDOWS]

### ISSUE THREAD

**Issue by luchillo17** [alexanderepstein/Insomnia#30] opened 2017-05-04 03:47 UTC
**Issue Label:** Bug

**Description of bug or feature enhancement:**
When updated to version 1.2.0 suddenly the default Wake-Up time doesn't get saved any more, i can go to the tray icon, open preferences from right click menu, set time to 5 am instead of the initial default 8:30, click the set button and close such window, if i go and open preferences again, the time is back to 8:30.

**OS and OS version:**
Win 10

**Version of Insomnia Application:**
1.2.0

**Comment by alexanderepstein** [comment] 2017-05-04 04:25
@luchillo17 
Interestingly enough i was able to reproduce your bug everytime, however when running the full source code uncompiled it works. For now I would say just downgrade to 1.2.0. I am planning on releasing version 1.3.0 tomorrow which contains a whole new way of storing the settings that is more reliable.

**Comment by alexanderepstein** [comment] 2017-05-04 12:21
@luchillo17 updated to 1.3.0

**Comment by luchillo17** [comment] 2017-05-04 16:26
Nice 😄

**Comment by luchillo17** [comment] 2017-05-05 00:19
@alexanderepstein Actually the app showed me a popup and sent me to the update page... of V1.2.0, maybe it's better to just send the user to the general releases url instead of the url of the next version, after all the most recent version will still be first in that url:
https://github.com/alexanderepstein/Insomnia/releases

**Comment by luchillo17** [comment] 2017-05-05 00:21
Tested V1.3.0 and settings save correctly, now what i see is that no matter what i choose, the time is always in military mode.

**Comment by alexanderepstein** [comment] 2017-05-05 00:28
@luchillo17 huh thats so weird since the default time preference and the military time preference both utilize the same logic. I did realize however i was sending the user to the current release of Insomnia and that still exists in 1.3.0. Just a variable name change and it should work now. I will have to test out the military time thing on a windows system to check out the console and see if and errors are thrown.

**Comment by luchillo17** [comment] 2017-05-05 02:30
What's broken is not the preferences save, is the display between military and default mode, if i change between them, the time still shows in military mode.

Btw could you make available the DevTools? most of us in github are developers, and we can help debug the issue if we can reach the DevTools, but so far i see no button and none standard keyboard shortcuts works.

**Comment by alexanderepstein** [comment] 2017-05-05 03:51
@luchillo17 I know what the issue is it has to do with the declaration of a different settings variable in main.js versus script.js. I need to implement a mixture between my old settings methodolgy and my new one. As for devtools I don't think it would look nice to have a button for it and when you don't have them set up to open the keyboard shortcuts doesn't work either. To see the devtools you'll have to clone electron cd to the folder run npm install then go into main.js and uncomment the two lines win.openDevtools and pref.openDevTools

**Comment by alexanderepstein** [comment] 2017-05-05 16:00
Hopefully all this is fixed in 1.4.0

**Closed by alexanderepstein** 2017-05-05 16:00 UTC
